### PR TITLE
Add tinycore

### PR DESCRIPTION
**Pull request by P0ly**
add basic support for Tiny Core Linux

### CODE REVIEW

**Comment by aguslr** [comment]
Hello P0ly,

It seems that some boot entries are missing from the config files. I was unable to boot into the desktop. Did you manage to do it with TinyCore-current.iso for instance?

BTW, thanks for the PR.

**Comment by P0ly** [comment]
That is something I still need to figure out.
But at least it is booting to the commandline.

**Comment by aguslr** [comment]
Yeah, I guessed it wasn't just me that couldn't get it to work.

If you could maybe change the menuentry to something like "*Boot Core (command line only)*" so it's clear that it's just the command line interface, I'll happily merge this.

**Comment by P0ly** [comment]
Sure no problem :)
Hope I can get the desktop to work sometime.
Found some articles in the FAQ that could help:  [http://distro.ibiblio.org/tinycorelinux/faq.html#bootcodes](url)
Also interesting: [http://distro.ibiblio.org/tinycorelinux/concepts.html](url)

**Comment by P0ly** [comment]
@aguslr Like your project by the way. Learned a lot from it. ;D
No really, I knew nearly nothing about grub and now I am liking it so much. 
Also like to be independent from programs that do this automatically, because of platform dependencies and incompatibility. Also it isn't a bad idea to know what is going on under hood to solve problems.

**Comment by aguslr** [comment]
Thanks @P0ly for making the changes and adding the entry to the README. I tried some of the bootcodes suggested in those links but I couldn't get the desktop working so we'll have to leave it like that for now.

> Also like to be independent from programs that do this automatically, because of platform dependencies and incompatibility. Also it isn't a bad idea to know what is going on under hood to solve problems.

That's exactly why I started this project: to learn more about what GRUB is doing under the hood.

And I too like the idea of using simple GRUB scripts for each ISO/distro instead of complex scripts to generate the files. This also encourages collaboration, I believe.

**Pull request merged**
