### PR TITLE
Allow setting data partition size.

### PR DESCRIPTION
**Pull request by chrisperelstein**
* Check for additional data partition size arg
* Pass data partition size arg to sgdisk

### CODE REVIEW

**Comment by chrisperelstein** [comment]
I have a bit of an odd reason reason for wanting this. This let's me limit the size of the data partition so I can great an additional (encrypted) partition for personal data, keeping isos and grub configs separate.

**Comment by aguslr** [comment]
Hi @chrisperelstein!

Your reason for wanting this is not odd at all. I think this would help those that want to set partitions for persistent data (e.g. for Kali, etc.).

However, when I run the script it fails with the following error:

```
./makeUSB.sh: 191: ./makeUSB.sh: datasize: parameter not set
```

**Comment by chrisperelstein** [comment]
Apologies for that. I blame my late night refactoring. Should be working now.

**Comment by aguslr** [comment]
Works great! Thanks.

**Pull request merged**
